services:
  production:
    # image: ghcr.io/SWAGSlides/SWAGSlides:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      # You can replace 5000 with any other port number of your choice to run SWAGSlides on a different port number.
      - "5000:80"
    volumes:
      - ./app_data:/app_data
    env_file:
      - .env

  production-gpu:
    # image: ghcr.io/SWAGSlides/SWAGSlides:latest
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      # You can replace 5000 with any other port number of your choice to run SWAGSlides on a different port number.
      - "5000:80"
    volumes:
      - ./app_data:/app_data
    env_file:
      - .env
  
  development:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5000:80"
    volumes:
      - .:/app
      - ./app_data:/app_data
    env_file:
      - .env

  development-gpu:
    build:
      context: .
      dockerfile: Dockerfile.dev
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - "5000:80"
    volumes:
      - .:/app
      - ./app_data:/app_data
    env_file:
      - .env